title: FallacyTag
description: FallacyTag is lightweight reasoning aid that surfaces flaws in argument structure.
theme: just-the-docs
color_scheme: light
url: https://coherentdrift.github.io/
baseurl: /fallacytag

mermaid:
  version: "9.1.3"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red  

aux_links:
  Substack: https://coherentdrift.substack.com
  GitHub: https://github.com/coherentdrift/fallacytag

collections:
  pages:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  logo: "/fallacytag/assets/images/logo.png"
  show_sidebar: true
  collections:
    pages:
      nav_exclude: false
      nav_fold: false 
